#Requires AutoHotkey v2.0

; caps to toggle ime
CapsLock::Send "#{Space}"

; remap shift + esc as tilde
+Escape::Send "~"

; remap RShift, RCtrl as scroll up and down
RShift::Send "{WheelUp}"
RCtrl::Send "{WheelDown}"

; use `alt + q` to toggle alacritty window visibility; generated by AI
!q::
{
    WinTitle := "ahk_exe alacritty.exe"
    if WinExist(WinTitle)
    {
        if WinActive(WinTitle)
            WinMinimize(WinTitle)
        else
            WinActivate(WinTitle)
    }
    else
    {
        Run("alacritty")
    }
}
